#!/bin/sh
# Reject grouped/depthwise convolutions in ConvOclDirectFwd's applicability
# check, so MIOpen never selects it (or its fused variant,
# ConvOclDirectFwdFused -> MIOpenConvUniBatchNormActiv) for them on gfx803.
#
# WHY
# ---
# MIOpenConvUniBatchNormActiv (src/kernels/MIOpenConvDirBatchNormActiv.cl,
# generated by ConvOclDirectFwd/ConvOclDirectFwdFused,
# src/solver/conv/conv_ocl_dir2Dfwd.cpp) does an out-of-bounds read on its
# weights buffer for grouped convolutions -- confirmed on real gfx803
# hardware (RX 470, ROCm 6.4.4) via a minimal, deterministic, standalone
# MIOpen repro (K=240 depthwise 3x3, groups=240, no ORT/model involved) that
# reliably faults on the very first execute. Root cause narrowed via
# AMD_SERIALIZE_KERNEL=3 (forces synchronous per-kernel execution, so a GPU
# page fault attributes to the exact kernel causing it instead of whichever
# kernel happened to be in flight when the fault surfaced) -- two
# independent captures of the real production crash (CLAP audio-encoder
# session churn) both attribute to this exact kernel, with the fault address
# landing 69KB-1.1MB past the end of the legitimately-allocated weights
# buffer depending on layer size. This is a genuine buffer overrun, not
# stale/uninitialized data.
#
# ConvOclDirectFwd::IsApplicable has a filter-size restriction gate that
# only applies `if (problem.GetGroupCount() == 1)` -- grouped convolutions
# skip that gate entirely and fall through to the final combined condition
# with no size/shape restriction specific to groups, reaching the same
# broken kernel that non-grouped convs use, without its own group-aware
# bounds correctness ever having been established.
#
# WHAT
# ----
# Reject GroupCount() != 1 outright in IsApplicable, so MIOpen routes
# grouped convs (fused or not) to a different solver instead. This is
# scoped to grouped convolutions only -- non-grouped shapes that
# legitimately want this solver are unaffected, unlike the blanket
# MIOPEN_DEBUG_CONV_DIRECT_OCL_FWD=0 env var this patch replaces (see
# KERNEL_BUGS.md for why that blunter fix was tried first and what this one
# improves on).
set -eu

SRC="${1:-/miopen-src}"
FILE="$SRC/src/solver/conv/conv_ocl_dir2Dfwd.cpp"

[ -f "$FILE" ] || { echo "FATAL: no conv_ocl_dir2Dfwd.cpp at $FILE" >&2; exit 1; }

already=$(grep -c 'CONV_DIRECT_FWD_GROUPED_OOB_PATCH' "$FILE" || true)
if [ "$already" -ne 0 ]; then
    echo "already patched, skipping"
    exit 0
fi

before=$(grep -c '// Factored out from ConvolutionDescriptor::IsDirectSupported(), which is now dissmissed:' "$FILE" || true)
if [ "$before" -ne 1 ]; then
    echo "FATAL: expected exactly 1 match for the IsApplicable insertion point in $FILE," >&2
    echo "       found $before -- upstream layout changed, re-check before patching." >&2
    exit 1
fi

python3 - "$FILE" <<'PYEOF'
import sys
path = sys.argv[1]
with open(path) as f:
    text = f.read()

needle = "    // Factored out from ConvolutionDescriptor::IsDirectSupported(), which is now dissmissed:\n"
replacement = (
    "    // CONV_DIRECT_FWD_GROUPED_OOB_PATCH: MIOpenConvUniBatchNormActiv has an\n"
    "    // out-of-bounds weights-buffer read for grouped convolutions on gfx803,\n"
    "    // confirmed via a minimal standalone repro and two independent\n"
    "    // AMD_SERIALIZE_KERNEL=3-attributed production crashes. This solver's own\n"
    "    // filter-size gate below only applies when GroupCount()==1, so grouped\n"
    "    // convs reach the broken kernel with no group-aware check at all. Reject\n"
    "    // them outright instead. See patches/miopen/conv-direct-fwd-grouped-oob.sh.\n"
    "    if(problem.GetGroupCount() != 1)\n"
    "        return false;\n\n"
    + needle
)

if needle not in text:
    print("FATAL: exact insertion point not found", file=sys.stderr)
    sys.exit(1)

text = text.replace(needle, replacement, 1)
with open(path, "w") as f:
    f.write(text)
print("patched")
PYEOF

after=$(grep -c 'CONV_DIRECT_FWD_GROUPED_OOB_PATCH' "$FILE" || true)
if [ "$after" -ne 1 ]; then
    echo "FATAL: patch marker not found after rewrite" >&2
    exit 1
fi
echo "Grouped-conv OOB patch applied to $FILE"
